# These are supported funding model platforms
# Uncomment and fill in the ones you use

# github: [your-github-username]
# ko_fi: your-ko-fi-username
# patreon: your-patreon-username
# open_collective: astralemu
# custom: ["https://your-link.com"]
